version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '13601:13601'
    env_file:
      - .env
    environment:
      DATABASE_URI: postgresql://payloadAdmin:${POSTGRES_PASSWORD}@172.17.0.1:13501/payloadDatabase
    network_mode: "bridge"