version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '13601:13601'
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: hankier-network
    driver: bridge