version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '13601:13601'
    env_file:
      - .env
    networks:
      - hankier-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '13501:5432'
    volumes:
      - /storage/hankier.pl/postgresDB_data:/var/lib/postgresql/data
    networks:
      - hankier-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payloadAdmin -d payloadDatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules:

networks:
  hankier-network:
    name: hankier-network
    driver: bridge